sample_list: "config/samples.csv"
mem_per_cpu: 6
read_length: 150
stpipelineLocation: "/crex/proj/snic2020-6-126/projects/masc_seq/st_pipeline"
assemblers:
  - "trinity"
  #- "transabyss"
cutadapt:
  R1_adapter: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  R2_adapter: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  minlen: 50
  # Extra sample-specific parameters
  sample_params:
    P21817_104: "-e 0.2"
sortmerna:
  dbs:
    - "silva-arc-16s-id95"
    - "silva-euk-28s-id98"
    - "rfam-5.8s-database-id98"
    - "rfam-5s-database-id98"
    - "silva-arc-23s-id98"
    - "silva-bac-16s-id90"
    - "silva-bac-23s-id98"
    - "silva-euk-18s-id95"
trinity:
  kmer: 32
  threads: 20
transabyss:
  kmer:
    - 32
    - 64
    - 96
  threads: 20
genome:
  Phaeodactylum:
    fasta: "/crex/proj/snic2020-6-126/projects/masc_seq/reference_genomes/Phaeodactylum_tricornutum/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa"
    gff: "/crex/proj/snic2020-6-126/projects/masc_seq/reference_genomes/Phaeodactylum_tricornutum/Phaeodactylum_tricornutum.ASM15095v2.48.chr.gff3"
  Tetrahymena:
    fasta: "/crex/proj/snic2020-6-126/projects/masc_seq/reference_genomes/Tetrahymena_thermophila/Tetra_Genome-assembly.fasta"
    gff: "/crex/proj/snic2020-6-126/projects/masc_seq/reference_genomes/Tetrahymena_thermophila/T.thermophila_genome.gff3"
transcriptome:
  Phaeodactylum:
    fasta: "results/genome/reference/Phaeodactylum_extractTranscriptsFromGenome.fasta.gz"
  Heterocapsa:
    fasta: "/crex/proj/snic2020-6-126/projects/masc_seq/LTS-A_Andersson_2010-MASCSEQ/results/trinity/P18363_103/P18363_103.filtered.fasta.gz"

busco:
  sample_lineages:
    P18363_101: "stramenopiles_odb10"
    P18363_103: "alveolata_odb10"
  lineages:
    alveolata_odb10:
      url: "https://busco-data.ezlab.org/v4/data/lineages/alveolata_odb10.2020-09-10.tar.gz"
    stramenopiles_odb10:
      url: "https://busco-data.ezlab.org/v4/data/lineages/stramenopiles_odb10.2020-08-05.tar.gz"
concatenate:
  - "resources/transcriptomeFromGenome/Tetrahymena.barrnap_filtered.fasta.gz"
  - "resources/transcriptomeFromGenome/Phaeodactylum.barrnap_filtered.fasta.gz"
  - "resources/transcriptome/Heterocapsa.fasta.gz"
transdecoder:
  # Added extra param option here to be able to set '--no_refine_starts':
  # start refinement identifies potential start codons for 5' partial ORFs using a PWM, process on by default.
  extra_params: ""
concatenateReads:
  env_300321.110521:
    - P21817_101
    - P21817_102
    - P21817_103
    - P21817_104