sample_list: "config/samples.csv"
mem_per_cpu: 6
assemblers:
  - "trinity"
  - "transabyss"
cutadapt:
  R1_adapter: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  R2_adapter: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  minlen: 50
sortmerna:
  dbs:
    - "silva-arc-16s-id95"
    - "silva-euk-28s-id98"
    - "rfam-5.8s-database-id98"
    - "rfam-5s-database-id98"
    - "silva-arc-23s-id98"
    - "silva-bac-16s-id90"
    - "silva-bac-23s-id98"
    - "silva-euk-18s-id95"
trinity:
  kmer: 32
  threads: 20
transabyss:
  kmer:
    - 32
    - 64
    - 96
  threads: 20
dammit:
  busco_group:
    P18363_101: "alveolata_stramenophiles" # Should be "stramenopiles"
    P18363_103: "alveolata_stramenophiles"
genome:
  Phaeodactylum:
    #fasta: "/crex/proj/snic2020-6-126/projects/masc_seq/reference_genomes/Phaeodactylum_tricornutum/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa"
    #gff: "/crex/proj/snic2020-6-126/projects/masc_seq/reference_genomes/Phaeodactylum_tricornutum/Phaeodactylum_tricornutum.ASM15095v2.48.chr.gff3"
    fasta: "data/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa"
    gff: "data/Phaeodactylum_tricornutum.ASM15095v2.48.chr.gff3"