sample_list: "config/samples.csv"
cutadapt:
  R1_adapter: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  R2_adapter: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
sortmerna:
  dbs:
    - "silva-arc-16s-id95"
    - "silva-euk-28s-id98"
    - "rfam-5.8s-database-id98"
    - "rfam-5s-database-id98"
    - "silva-arc-23s-id98"
    - "silva-bac-16s-id90"
    - "silva-bac-23s-id98"
    - "silva-euk-18s-id95"