$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  sample_list:
    type: string
    description: "Path to a sample sheet"
    default: "config/samples.csv"
  mem_per_cpu:
    type: integer
    description: "Memory in GB per CPU"
    default: 6
  cutadapt:
    type: object
    default:
      R1_adapter: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
      R2_adapter: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
    properties:
      R1_adapter:
        type: string
        description: Fwd adapter for cutadapt
      R2_adapter:
        type: string
        description: Rev adapter for cutadapt
  sortmerna:
    type: object
    default:
      dbs:
        - "rfam-5s-database-id98"
        - "rfam-5.8s-database-id98"
        - "silva-arc-16s-id95"
        - "silva-arc-23s-id98"
        - "silva-bac-16s-id90"
        - "silva-bac-23s-id98"
        - "silva-euk-18s-id95"
        - "silva-euk-28s-id98"
    properties:
      dbs:
        type: array
        description: "Databases to use for rRNA identification"
        items:
          type: string
  trinity:
    type: object
    default:
      kmer: 32
      threads: 20
    properties:
      kmer:
        type: integer
        description: "Kmer size to use for trinity"
      threads:
        type: integer
        description: "Threads to use for trinity"
  transabyss:
    type: object
    default:
      kmer:
        - 32
        - 64
        - 96
      threads: 20
    properties:
      kmer:
        type: array
        description: "Kmer sizes to use for transabyss"
        items:
          type: integer
      threads:
        type: integer
        description: "Threads to use for transabyss"